import { PROFILE } from '../data/profile'

function PageShell({ title, children }) {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12">
      <a className="pixel-btn mb-8 inline-block !text-[10px]" href="/">← BACK TO THE GAME</a>
      <h1 className="mb-6 text-sm text-pix-yellow">{title}</h1>
      <div className="space-y-4 font-body text-sm leading-relaxed text-ink-dim [&_h2]:font-pixel [&_h2]:text-[10px] [&_h2]:text-neon [&_h2]:pt-2">
        {children}
      </div>
    </main>
  )
}

export function PrivacyPage() {
  return (
    <PageShell title="PRIVACY POLICY">
      <p>
        This is the personal portfolio of {PROFILE.name}. It collects as little
        as possible — here is exactly what happens to your data, in plain words.
        Last updated: July 2026.
      </p>
      <h2>GAME SAVE (LOCALSTORAGE)</h2>
      <p>
        Your XP, level, achievements and settings are stored only in your own
        browser (localStorage key <code>qa-portfolio-save-v1</code>). They never
        leave your device. &quot;Reset Save&quot; in the menu deletes them. No
        cookies are used for this, and no account exists.
      </p>
      <h2>BUGSY CHAT (AI)</h2>
      <p>
        Messages you type to Bugsy are sent to this site&apos;s server function
        and forwarded to Google&apos;s Gemini API to generate a reply, subject to
        Google&apos;s API terms. Don&apos;t include personal or sensitive data in
        chat messages. Conversations are not stored by this site — each request
        only carries your recent messages from the current visit.
      </p>
      <h2>QUIZ GENERATOR (AI)</h2>
      <p>
        The Learning Game requests AI-generated quizzes from the same Gemini
        API. Only the topic and difficulty are sent — nothing about you.
      </p>
      <h2>CONTACT FORM (WEB3FORMS)</h2>
      <p>
        The &quot;Send a Raven&quot; form is delivered by Web3Forms, which
        processes the name, email and message you submit in order to email them
        to Soyed. Alternatively, just email {PROFILE.email} directly.
      </p>
      <h2>BOOKING (CALENDLY)</h2>
      <p>
        The &quot;Party Up&quot; calendar is an embedded Calendly widget, loaded
        only when you open it. Data you enter there is processed by Calendly
        under Calendly&apos;s own privacy policy.
      </p>
      <h2>JOB QUEST BOARD</h2>
      <p>
        Job listings are fetched from public job aggregators (JSearch / Google
        for Jobs) by this site&apos;s server. Your search text stays in your
        browser; only the category is sent to the server.
      </p>
      <h2>ANALYTICS</h2>
      <p>
        This site uses Vercel Analytics — a cookieless, privacy-respecting
        counter of page views and anonymous game events (like &quot;section
        opened&quot;). It does not identify you or track you across sites.
        Because no non-essential cookies or cross-site trackers exist here, no
        cookie consent banner is required.
      </p>
      <h2>QUESTIONS</h2>
      <p>
        Email <a className="text-neon underline" href={`mailto:${PROFILE.email}`}>{PROFILE.email}</a> — a human reads it.
      </p>
    </PageShell>
  )
}

export function TermsPage() {
  return (
    <PageShell title="TERMS & CONDITIONS">
      <p>
        Welcome, adventurer. Short version: this is a personal portfolio and a
        free learning toy — play nice. Last updated: July 2026.
      </p>
      <h2>WHAT THIS SITE IS</h2>
      <p>
        The personal, non-commercial portfolio of {PROFILE.name}. Nothing here
        is professional, legal, or career advice, and nothing is sold.
      </p>
      <h2>AI-GENERATED CONTENT</h2>
      <p>
        Quizzes and Bugsy&apos;s chat replies are generated by an AI model. They
        are a learning aid, provided &quot;as is&quot;, with no warranty of
        accuracy or completeness — verify anything important independently.
        Bugsy can make mistakes; when in doubt, ask Soyed directly.
      </p>
      <h2>JOB LISTINGS</h2>
      <p>
        The Job Quest Board shows listings from third-party public job
        aggregators. This site does not create, verify, or guarantee any
        listing. Freshness and accuracy may vary — always confirm details on the
        original posting before applying.
      </p>
      <h2>ACCEPTABLE USE</h2>
      <p>
        Don&apos;t abuse the chat or quiz endpoints (rate limits apply),
        don&apos;t attempt to attack the site, and don&apos;t use it to harass
        anyone. Trying to make Bugsy misbehave is fine as a sport — he&apos;s
        been tested for it — but automated abuse will be blocked.
      </p>
      <h2>LIABILITY</h2>
      <p>
        Provided free of charge, &quot;as is&quot;, with no warranties. To the
        maximum extent permitted by law, {PROFILE.name} is not liable for any
        damages arising from using this site. If a bug ate your XP, report it —
        an SQA engineer genuinely wants to know.
      </p>
      <h2>CONTACT</h2>
      <p>
        <a className="text-neon underline" href={`mailto:${PROFILE.email}`}>{PROFILE.email}</a>
      </p>
    </PageShell>
  )
}

export function GameOverPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-6 p-6 text-center">
      <p className="text-6xl" aria-hidden="true">👾</p>
      <h1 className="text-xl text-danger sm:text-3xl">GAME OVER</h1>
      <p className="font-pixel text-[10px] leading-relaxed text-ink-dim sm:text-xs">
        LEVEL NOT FOUND — this path leads off the map.
      </p>
      <a className="pixel-btn !border-pix-yellow !text-xs" href="/">
        ▶ INSERT COIN (BACK TO START)
      </a>
    </main>
  )
}
